####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

###  Global configuration ###
#  Note that `customize` is nested within `homeassistant`.

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 158
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  
http:
  api_password: !secret api_password

####################################################
#                                                  #
#                  Components                      #
#                                                  #
####################################################

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Track the sun
sun:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
conversation:

# Prediction of weather
#sensor:
#   platform: yr

light:
  platform: lifx
  server: !secret lifx_ip
  
wink:
  access_token: !secret wink_access_token

ifttt:
  key: !secret ifttt_key

group:
  home:
    view: yes
    entities:
      - updater.updater
      - light.porch_light
      - binary_sensor.front_door
      - binary_sensor.back_door
      - binary_sensor.basement_door
      - sun.sun
      - sensor.plex_spy
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - device_tracker.james_nexus6p
      - device_tracker.androidabd572ceca26d5b0cincirrcom
  living_room_fan_lights:
    name: Living Room Fan Lights
    entities:
      - light.living_room_fan_front
      - light.living_room_fan_left
      - light.living_room_fan_rear
      - light.living_room_fan_right
  living_room:
    name: Living Room
    view: yes
    entities:
      - binary_sensor.living_room
      - group.living_room_fan_lights
      - switch.living_room_entertainment_center
      - media_player.1st_gen
      - media_player.nexus_player
      - media_player.roku_1gh31x043774
  kitchen:
    name: Kitchen
    view: yes
    entities:
      - binary_sensor.kitchen
      - switch.kitchen_cabinets
  james_ceiling_fan_lights:
    name: James Ceiling Fan Lights
    entities:
      - light.james_ceiling_fan
      - light.james_fan_front_daylight
      - light.james_fan_left_soft
      - light.james_fan_right_soft
  james_bed_lights:
    name: James Bed Lights
    entities:
      - light.james_bed_left
      - light.james_bed_right
  james_lightstrips:
    name: James Light Strips
    entities:
      - light.james_bed_left
      - light.james_bed_right
      - light.james_dresser
  james_presence:
    name: James' Presence
    entities:
      - device_tracker.james_nexus6p
      - device_tracker.jamesmbp
      - device_tracker.james_work_phone
      - device_tracker.james_work_mbp
  james:
    name: James' Room
    view: yes
    entities:
      - group.james_presence
      - group.james_ceiling_fan_lights
      - group.james_bed_lights
      - group.james_lightstrips
      - light.james_closet
      - scene.romantic
      - scene.movies
      - scene.wakeup
      - scene.bedtime
      - scene.morning_lights
      - input_boolean.bedtime
      - device_tracker.james_nexus6p
      - device_tracker.jamesmbp
  james_fitness:
    name: James' Fitness
    entities:
      - sensor.activitycalories
      - sensor.bmi
      - sensor.body_fat
      - sensor.body_weight
      - sensor.calories
      - sensor.caloriesbmr
      - sensor.distance
      - sensor.elevation
      - sensor.floors
      - sensor.heart
      - sensor.minutesfairlyactive
      - sensor.minuteslightlyactive
      - sensor.minutessedentary
      - sensor.minutesveryactive
      - sensor.sleep_awakeningscount
      - sensor.sleep_efficiency
      - sensor.sleep_minutesafterwakeup
      - sensor.sleep_minutesasleep
      - sensor.sleep_minutesawake
      - sensor.sleep_minutestofallasleep
      - sensor.sleep_starttime
      - sensor.sleep_timeinbed
      - sensor.steps
      - sensor.tracker_activitycalories
      - sensor.tracker_calories
      - sensor.tracker_steps
  clay:
    name: Clay
    view: yes
    entities:
      - group.clay_fan_lights
      - group.clay_presence
      - device_tracker.androidabd572ceca26d5b0cincirrcom
      - device_tracker.bfmc02mq6bgfh00
      - device_tracker.rorycincirrcom
  clay_fan_lights:
    name: Clay's Fan Lights
    entities:
      - light.clay_fan_1
      - light.clay_fan_2
      - light.clay_fan_3
      - light.clay_fan_4
  clay_presence:
    name: Clay's Presence
    entities:
      - device_tracker.androidabd572ceca26d5b0cincirrcom
      - device_tracker.bfmc02mq6bgfh00
  sam:
    name: Sam's Room
    entities:
      - device_tracker.samsmbpcincirrcom
  office:
    name: Office
    view: yes
    entities:
      - light.james_office_desk
  weather:
    name: Weather
    view: yes
    entities:
      - sensor.forecastio_apparent_temperature
      - sensor.forecastio_cloud_coverage
      - sensor.forecastio_daily_summary
      - sensor.forecastio_dew_point
      - sensor.forecastio_hourly_summary
      - sensor.forecastio_humidity
      - sensor.forecastio_icon
      - sensor.forecastio_minutely_summary
      - sensor.forecastio_nearest_storm_bearing
      - sensor.forecastio_nearest_storm_distance
      - sensor.forecastio_ozone
      - sensor.forecastio_precip
      - sensor.forecastio_precip_intensity
      - sensor.forecastio_precip_probability
      - sensor.forecastio_pressure
      - sensor.forecastio_summary
      - sensor.forecastio_temperature
      - sensor.forecastio_visibility
      - sensor.forecastio_wind_bearing
      - sensor.forecastio_wind_speed
      - sun.sun
  health:
    name: Health
    view: yes
    entities:
      - group.james_fitness
  media:
    name: Media
    view: yes
    entities:
      - media_player.1st_gen
      - media_player.2nd_gen
      - media_player.nexus_player
      - media_player.roku_1gh31x043774
  links:
    name: Links
    view: yes
    entities:
      - weblink.home_assistant
      - weblink.plex
      - weblink.couchpotato
      - weblink.sonarr
      - weblink.nzbget
      - weblink.dognzb
      - weblink.router

sensor:
  - platform: nzbget
    host: home.gissendaner.com
    port: 6789
    username: !secret nzbget_username
    password: !secret nzbget_password
    monitored_variables:
      - article_cache
      - average_download_rate
      - download_paused
      - download_rate
      - download_size
      - free_disk_space
      - post_paused
      - remaining_size
      - uptime

  # - platform: rest
    # resource: http://home.gissendaner.com:8003/userlocs?group=vivianlane&user=james
    # value_template: '{{ value_json.users.james.location }}{{ value_json.users.james.time }}'
    # method: GET
    # name: FIND location sensor
    # scan_interval: 3
  - platform: plex
    name: Plex Spy
    host: 192.168.86.50
    port: 32400
    username: !secret plex_username
    password: !secret plex_password
    server: leviathan
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: forecast
    api_key: !secret forcast_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
  - platform: fitbit
    monitored_resources:
      - "activities/activityCalories"
      - "activities/calories"
      - "activities/caloriesBMR"
      - "activities/distance"
      - "activities/elevation"
      - "activities/floors"
      - "activities/heart"
      - "activities/minutesFairlyActive"
      - "activities/minutesLightlyActive"
      - "activities/minutesSedentary"
      - "activities/minutesVeryActive"
      - "activities/steps"
      - "activities/tracker/activityCalories"
      - "activities/tracker/calories"
      - "activities/tracker/distance"
      - "activities/tracker/elevation"
      - "activities/tracker/floors"
      - "activities/tracker/minutesFairlyActive"
      - "activities/tracker/minutesLightlyActive"
      - "activities/tracker/minutesSedentary"
      - "activities/tracker/minutesVeryActive"
      - "activities/tracker/steps"
      - "body/bmi"
      - "body/fat"
      - "body/weight"
      - "sleep/awakeningsCount"
      - "sleep/efficiency"
      - "sleep/minutesAfterWakeup"
      - "sleep/minutesAsleep"
      - "sleep/minutesAwake"
      - "sleep/minutesToFallAsleep"
      - "sleep/startTime"
      - "sleep/timeInBed"
      
mqtt:
  broker: 192.168.86.50
  port: 8883
  client_id: home-assistant-1
  keepalive: 60
  username: haas
  
device_tracker:
  #- platform: ddwrt
  #  host: 192.168.1.1
  #  username: !secret router_username
  #  password: !secret router_password
    # If new discovered devices are tracked by default (default: yes)
  #  track_new_devices: no
    # Seconds between each scan for new devices (default: 12)
  #  interval_seconds: 12
    # Seconds to wait till marking someone as not home after not being seen
    # (default: 180)
  #  consider_home: 180
  - platform: owntracks
    waypoints: True
    max_gps_accuracy: 200
  # - platform: nmap_tracker
    # hosts: 192.168.1.1/24
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    username: !secret automatic_username
    password: !secret automatic_password

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#general'
  - name: autoremote
    platform: rest
    resource: !secret autoremote_link

input_boolean:
  bedtime:
    name: Time for Bed
    initial: off
    icon: mdi:hotel

###  Scenes  ###
scene: !include scenes.yaml

###  Weblinks  ###
weblink: !include weblink.yaml

###  Automation  ###
automation: !include_dir_merge_list automation
switch:
  platform: flux
  lights:
    - light.james_office_desk
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  mode: xy

panel_iframe:
  couchpotato:
    title: 'CouchPotato'
    icon: 'mdi:movie'
    url: 'http://home.gissendaner.com:5050'
  nzbget:
    title: 'NZBGet'
    icon: 'mdi:cloud-download'
    url: 'http://home.gissendaner.com:6789'
  sonarr:
    title: 'Sonarr'
    icon: 'mdi:television'
    url: 'http://home.gissendaner.com:8989'
  plex:
    title: 'Plex'
    icon: 'mdi:youtube-play'
    url: 'http://home.gissendaner.com:32400/web'