- alias: porch_sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: light.turn_on
    entity_id: light.porch_light
- alias: porch_sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  action:
    service: light.turn_off
    entity_id: light.porch_light